export type ActiveSection =
  | 'home'
  | 'recallradar'
  | 'drugsignal'
  | 'foodradar'
  | 'cosmeticsignal'

export type ActivePage =
  | 'home'
  | 'pharmacy-safety'
  | 'food-safety'
  | 'cosmetic-safety'
  | 'sources'
  | 'audit'
  | 'system'
  | 'saved-monitors'
  | 'regional-health'
  | 'about'
  | 'faq'
  | 'help'