export type ActivePage =
  | 'home'
  | 'pharmacy-safety'
  | 'food-safety'
  | 'cosmetic-safety'
  | 'productscan'
  | 'sources'
  | 'audit'
  | 'system'
  | 'saved-monitors'
  | 'regional-health'
  | 'about'
  | 'faq'
  | 'help'
